version: 1
default_environment: dev
project_id: 9b56a65d-51d4-400e-99c7-178e642876ef
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
    config:
      dbname: dbnorthwind
      default_replication_method: FULL_TABLE
      filter_schemas: public
      host: localhost
      port: 5432
      user: postgres
  loaders:
  - name: target-csv
    variant: hotgluexyz
    pip_url: git+https://github.com/hotgluexyz/target-csv.git
    config:
      destination_path: ./csv_first_output
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
      --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
jobs:
- name: tap-postgres-to-target-csv-
  tasks:
  - tap-postgres target-csv
schedules:
- name: daily-gitlab-load
  interval: '@daily'
  job: tap-gitlab-to-target-postgres-with-dbt
