version: 1
default_environment: dev
project_id: bed1568e-eccf-402a-bbe7-611d4bdd2c5b
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - path: ../first_step/csv_first_output/order_details.csv
        entity: order_details
        keys:
        - id
      - path: ../first_step/csv_first_output/public-categories-20240611T015148.csv
        entity: categories
        keys:
        - id
      - path: ../first_step/csv_first_output/public-customers-20240611T015148.csv
        entity: customers
        keys:
        - id
      - path: ../first_step/csv_first_output/public-employees-20240611T015148.csv
        entity: employees
        keys:
        - id
      - path: ../first_step/csv_first_output/public-employee_territories-20240611T015148.csv
        entity: employee_territories
        keys:
        - id
      - path: ../first_step/csv_first_output/public-orders-20240611T015148.csv
        entity: orders
        keys:
        - id
      - path: ../first_step/csv_first_output/public-products-20240611T015148.csv
        entity: products
        keys:
        - id
      - path: ../first_step/csv_first_output/public-region-20240611T015148.csv
        entity: region
        keys:
        - id
      - path: ../first_step/csv_first_output/public-shippers-20240611T015148.csv
        entity: shippers
        keys:
        - id
      - path: ../first_step/csv_first_output/public-suppliers-20240611T015148.csv
        entity: suppliers
        keys:
        - id
      - path: ../first_step/csv_first_output/public-territories-20240611T015148.csv
        entity: territories
        keys:
        - id
      - path: ../first_step/csv_first_output/public-us_states-20240611T015148.csv
        entity: us_states
        keys:
        - id
    select:
    - '*.*'
    - '*.*'
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    config:
      dbname: target
      primary_key_required: false
      user: postgres
      host: localhost
      port: 5432
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
      --constraint 
      https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
schedules:
- name: tap-csv-to-target-postgres
  interval: '@daily'
  job: tap-csv-to-target-postgres
jobs:
- name: tap-csv-to-target-postgres
  tasks:
  - tap-csv target-postgres
